{
  "Best Practices": {
    "suggestion": {
      "accessor-pairs": "off",
      "block-scoped-var": "off",
      "class-methods-use-this": "off",
      "complexity": "off",
      "consistent-return": "off",
      "curly": "off",
      "default-case": "off",
      "dot-notation": "off",
      "eqeqeq": "off",
      "guard-for-in": "off",
      "max-classes-per-file": "off",
      "no-alert": "off",
      "no-caller": "off",
      "no-case-declarations": "off",
      "no-div-regex": "off",
      "no-else-return": "off",
      "no-empty-function": "off",
      "no-eq-null": "off",
      "no-eval": "off",
      "no-extend-native": "off",
      "no-extra-bind": "off",
      "no-extra-label": "off",
      "no-floating-decimal": "off",
      "no-global-assign": "off",
      "no-implicit-coercion": "off",
      "no-implicit-globals": "off",
      "no-implied-eval": "off",
      "no-invalid-this": "off",
      "no-iterator": "off",
      "no-labels": "off",
      "no-lone-blocks": "off",
      "no-loop-func": "off",
      "no-magic-numbers": "off",
      "no-multi-str": "off",
      "no-native-reassign": "off",
      "no-new": "off",
      "no-new-func": "off",
      "no-new-wrappers": "off",
      "no-octal": "off",
      "no-octal-escape": "off",
      "no-param-reassign": "off",
      "no-proto": "off",
      "no-redeclare": "off",
      "no-restricted-properties": "off",
      "no-return-assign": "off",
      "no-return-await": "off",
      "no-script-url": "off",
      "no-sequences": "off",
      "no-throw-literal": "off",
      "no-unused-expressions": "off",
      "no-unused-labels": "off",
      "no-useless-call": "off",
      "no-useless-catch": "off",
      "no-useless-concat": "off",
      "no-useless-escape": "off",
      "no-useless-return": "off",
      "no-void": "off",
      "no-warning-comments": "off",
      "no-with": "off",
      "prefer-promise-reject-errors": "off",
      "radix": "off",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "vars-on-top": "off",
      "yoda": "off"
    },
    "problem": {
      "array-callback-return": "off",
      "no-empty-pattern": "off",
      "no-fallthrough": "off",
      "no-self-assign": "off",
      "no-self-compare": "off",
      "no-unmodified-loop-condition": "off"
    },
    "layout": {
      "dot-location": "off",
      "no-multi-spaces": "off",
      "wrap-iife": "off"
    }
  },
  "Stylistic Issues": {
    "layout": {
      "array-bracket-newline": "off",
      "array-bracket-spacing": "off",
      "array-element-newline": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "comma-dangle": "off",
      "comma-spacing": "off",
      "comma-style": "off",
      "computed-property-spacing": "off",
      "eol-last": "off",
      "func-call-spacing": "off",
      "function-paren-newline": "off",
      "implicit-arrow-linebreak": "off",
      "indent": "off",
      "indent-legacy": "off",
      "jsx-quotes": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "line-comment-position": "off",
      "linebreak-style": "off",
      "lines-around-comment": "off",
      "lines-around-directive": "off",
      "lines-between-class-members": "off",
      "max-len": "off",
      "max-statements-per-line": "off",
      "multiline-ternary": "off",
      "new-parens": "off",
      "newline-after-var": "off",
      "newline-before-return": "off",
      "newline-per-chained-call": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-multiple-empty-lines": "off",
      "no-spaced-func": "off",
      "no-tabs": "off",
      "no-trailing-spaces": "off",
      "no-whitespace-before-property": "off",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": "off",
      "object-property-newline": "off",
      "operator-linebreak": "off",
      "padded-blocks": "off",
      "padding-line-between-statements": "off",
      "quotes": "off",
      "semi": "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "switch-colon-spacing": "off",
      "template-tag-spacing": "off",
      "unicode-bom": "off",
      "wrap-regex": "off"
    },
    "suggestion": {
      "camelcase": "off",
      "capitalized-comments": "off",
      "consistent-this": "off",
      "func-name-matching": "off",
      "func-names": "off",
      "func-style": "off",
      "id-blacklist": "off",
      "id-length": "off",
      "id-match": "off",
      "max-depth": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements": "off",
      "multiline-comment-style": "off",
      "new-cap": "off",
      "no-array-constructor": "off",
      "no-bitwise": "off",
      "no-continue": "off",
      "no-inline-comments": "off",
      "no-lonely-if": "off",
      "no-mixed-operators": "off",
      "no-multi-assign": "off",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new-object": "off",
      "no-plusplus": "off",
      "no-restricted-syntax": "off",
      "no-ternary": "off",
      "no-underscore-dangle": "off",
      "no-unneeded-ternary": "off",
      "one-var": "off",
      "one-var-declaration-per-line": "off",
      "operator-assignment": "off",
      "prefer-object-spread": "off",
      "quote-props": "off",
      "require-jsdoc": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "spaced-comment": "off"
    }
  },
  "ECMAScript 6": {
    "suggestion": {
      "arrow-body-style": "off",
      "no-confusing-arrow": "off",
      "no-restricted-imports": "off",
      "no-useless-computed-key": "off",
      "no-useless-constructor": "off",
      "no-useless-rename": "off",
      "no-var": "off",
      "object-shorthand": "off",
      "prefer-arrow-callback": "off",
      "prefer-const": "off",
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "off",
      "prefer-reflect": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "require-yield": "off",
      "sort-imports": "off",
      "symbol-description": "off"
    },
    "layout": {
      "arrow-parens": "off",
      "arrow-spacing": "off",
      "generator-star-spacing": "off",
      "rest-spread-spacing": "off",
      "template-curly-spacing": "off",
      "yield-star-spacing": "off"
    },
    "problem": {
      "constructor-super": "off",
      "no-class-assign": "off",
      "no-const-assign": "off",
      "no-dupe-class-members": "off",
      "no-duplicate-imports": "off",
      "no-new-symbol": "off",
      "no-this-before-super": "off"
    }
  },
  "Node.js and CommonJS": {
    "suggestion": {
      "callback-return": "off",
      "global-require": "off",
      "handle-callback-err": "off",
      "no-mixed-requires": "off",
      "no-new-require": "off",
      "no-path-concat": "off",
      "no-process-env": "off",
      "no-process-exit": "off",
      "no-restricted-modules": "off",
      "no-sync": "off"
    },
    "problem": {
      "no-buffer-constructor": "off"
    }
  },
  "Possible Errors": {
    "problem": {
      "for-direction": "off",
      "getter-return": "off",
      "no-async-promise-executor": "off",
      "no-await-in-loop": "off",
      "no-compare-neg-zero": "off",
      "no-cond-assign": "off",
      "no-constant-condition": "off",
      "no-control-regex": "off",
      "no-debugger": "off",
      "no-dupe-args": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-empty-character-class": "off",
      "no-ex-assign": "off",
      "no-func-assign": "off",
      "no-inner-declarations": "off",
      "no-invalid-regexp": "off",
      "no-irregular-whitespace": "off",
      "no-misleading-character-class": "off",
      "no-negated-in-lhs": "off",
      "no-obj-calls": "off",
      "no-prototype-builtins": "off",
      "no-sparse-arrays": "off",
      "no-template-curly-in-string": "off",
      "no-unexpected-multiline": "off",
      "no-unreachable": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "require-atomic-updates": "off",
      "use-isnan": "off",
      "valid-typeof": "off"
    },
    "suggestion": {
      "no-console": "off",
      "no-empty": "off",
      "no-extra-boolean-cast": "off",
      "no-extra-semi": "off",
      "no-regex-spaces": "off",
      "valid-jsdoc": "off"
    },
    "layout": {
      "no-extra-parens": "off"
    }
  },
  "Variables": {
    "suggestion": {
      "init-declarations": "off",
      "no-catch-shadow": "off",
      "no-delete-var": "off",
      "no-label-var": "off",
      "no-restricted-globals": "off",
      "no-shadow": "off",
      "no-shadow-restricted-names": "off",
      "no-undef-init": "off",
      "no-undefined": "off"
    },
    "problem": {
      "no-undef": "off",
      "no-unused-vars": "off",
      "no-use-before-define": "off"
    }
  },
  "Strict Mode": {
    "suggestion": {
      "strict": "off"
    }
  }
}